apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-playground-app
  template:
    metadata:
      labels:
        app: ai-playground-app
    spec:
      containers:
      - name: ai-playground-app
        image: quay.io/arosa/ai-playground:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-playground-app-service
spec:
  selector:
    app: ai-playground-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

